"""Add new table

Revision ID: 5e4a38fc1bd5
Revises: 241243d9f2ca
Create Date: 2024-07-17 17:13:11.145965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4a38fc1bd5'
down_revision: Union[str, None] = '241243d9f2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('positive_feedback', sa.Text(), nullable=True),
    sa.Column('best_practice_code', sa.Text(), nullable=True),
    sa.Column('best_practice_explanation', sa.Text(), nullable=True),
    sa.Column('source_language', sa.String(length=50), nullable=True),
    sa.Column('target_language', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['profile.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Text(), nullable=True),
    sa.Column('efficiency', sa.Text(), nullable=True),
    sa.Column('readability', sa.Text(), nullable=True),
    sa.Column('pep8_compliance', sa.Text(), nullable=True),
    sa.Column('modularity_reusability', sa.Text(), nullable=True),
    sa.Column('exception_handling', sa.Text(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('efficiency', sa.Integer(), nullable=True),
    sa.Column('readability', sa.Integer(), nullable=True),
    sa.Column('pep8_compliance', sa.Integer(), nullable=True),
    sa.Column('modularity_reusability', sa.Integer(), nullable=True),
    sa.Column('exception_handling', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_input_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_input_codes')
    op.drop_table('suggestions')
    op.drop_table('score_details')
    op.drop_table('feedback_details')
    op.drop_table('grade')
    # ### end Alembic commands ###
