"""create quiz table

Revision ID: 9ab0e2532fb6
Revises: 
Create Date: 2024-07-03 14:30:33.619487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab0e2532fb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_language', sa.String(length=50), nullable=False),
    sa.Column('target_language', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.Column('category_detail', sa.String(length=100), nullable=False),
    sa.Column('quiz', sa.Text(), nullable=False),
    sa.Column('hint_source_language_code', sa.Text(), nullable=False),
    sa.Column('hint_description', sa.Text(), nullable=False),
    sa.Column('answer_code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    # ### end Alembic commands ###
